import { readFile, readdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
for (const file of ['package.json', 'graph.json', 'models.lock.json', 'benchmarks/schema.json']) JSON.parse(await readFile(resolve(root, file), 'utf8'))
const metadata = JSON.parse(await readFile(resolve(root, 'package.json'), 'utf8'))
if (metadata.publishConfig?.access !== 'public') throw new Error('scoped npm package must publish publicly')
if (metadata.publishConfig?.registry !== 'https://registry.npmjs.org/') throw new Error('npm release registry is not pinned')
const graph = JSON.parse(await readFile(resolve(root, 'graph.json'), 'utf8'))
const modelLock = JSON.parse(await readFile(resolve(root, 'models.lock.json'), 'utf8'))
const graphText = JSON.stringify(graph)
const modelText = JSON.stringify(modelLock)
if (graphText.toLowerCase().includes('kokoro') || modelText.toLowerCase().includes('kokoro')) throw new Error('Kokoro remains in the runtime contract')
if (!graph.nodes.some(node => node.node_type === 'muxiva.qwen3_tts')) throw new Error('Qwen3-TTS Node Pack is not wired into the graph')
const vad = graph.nodes.find(node => node.node_type === 'muxiva.sherpa_vad_asr')
if (!vad || vad.node_config.vad_threshold < 0.7 || vad.node_config.min_speech_seconds < 0.02) throw new Error('VAD false-trigger guardrails are missing')
if (vad.node_config.min_silence_seconds < 0.35 || vad.node_config.min_silence_seconds > 0.75) throw new Error('low-latency conversational ASR endpoint is missing')
if (vad.node_config.barge_in_min_chars < 1) throw new Error('ASR-confirmed barge-in is not configured')
if (vad.node_config.barge_in_vad_hold_ms < 0 || vad.node_config.barge_in_vad_hold_ms > 40) throw new Error('sustained-VAD barge-in guardrail is missing')
const tts = graph.nodes.find(node => node.node_type === 'muxiva.qwen3_tts')
if (tts?.node_config.speaker !== 'Serena') throw new Error('warm gentle Mandarin TTS voice is not configured')
if (tts?.node_config.playback_lookahead_ms < 120 || tts?.node_config.playback_lookahead_ms > 180) throw new Error('bounded TTS playback lookahead is missing')
if (!modelLock.models.some(model => model.id === 'qwen3-tts-12hz-0.6b-customvoice-8bit')) throw new Error('pinned Qwen3-TTS model is missing')
const nodeDirs = await readdir(resolve(root, '.muxiva/nodes'))
if (nodeDirs.length !== 7) throw new Error(`expected seven project Node Packs, found ${nodeDirs.length}`)
for (const directory of nodeDirs) JSON.parse(await readFile(resolve(root, '.muxiva/nodes', directory, 'muxiva.node.json'), 'utf8'))
const client = await readFile(resolve(root, 'lib/client.js'), 'utf8')
if (!client.startsWith('window.__ModuleLoader__.load({')) throw new Error('DSH browser artifact lacks the module-loader handoff')
if (!client.includes("id: '@muxiva/dsh-voice'")) throw new Error('DSH browser artifact id mismatch')
if (!client.includes("this.send(muted ? 'client.mute' : 'client.unmute')")) throw new Error('persistent microphone mute control is missing')
if (!client.includes("if (!muted && this.socket?.readyState === WebSocket.OPEN)")) throw new Error('muted browser audio must not be admitted')
if (client.includes("new ArrayBuffer(event.data.pcm.byteLength)")) throw new Error('mute must pause the Source instead of injecting zero PCM')
if (!client.includes("message.type === 'asr.rejected'")) throw new Error('empty ASR recovery is missing')
if (!graph.edges.some(edge => edge.id === 'microphone-source-state-to-asr')) throw new Error('Source pause boundary is not routed to VAD/ASR')
console.log('package contracts verified')
